[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run build && npx serve -s build --listen $PORT --no-clipboard --no-port-switching"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 3000

[build.env]
NODE_ENV = "production"
PUBLIC_URL = "https://frontend-production-8b85.up.railway.app"