[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm install -g serve && serve -s build"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"