[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node -e \"require('http').createServer((req, res) => require('fs').readFile('build' + (req.url === '/' ? '/index.html' : req.url), (err, data) => { if (err) { res.writeHead(404); res.end('Not found'); } else { res.end(data); } })).listen(process.env.PORT || 3000)\""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"