[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 80

[build.env]
NODE_ENV = "production"
PUBLIC_URL = "https://frontend-production-8b85.up.railway.app"