[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "cd frontend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[start]
startCommand = "npm start"
