[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 80
healthcheck_path = "/"
healthcheck_timeout = 100

[build.env]
NODE_ENV = "production"
CI = "false"