[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm start"

[deploy]
startCommand = "cd frontend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
