[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run build && npx serve -s build"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 3000