[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "npm run build && npx serve -s build --listen $PORT --no-clipboard"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 3000

[build.env]
NODE_ENV = "production"
CI = "false"